# Generated by Django 5.1.6 on 2025-03-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_user_delete_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pdf_file", models.FileField(upload_to="pdf_files/")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
